### ISSUE TITLE
Could you share the training code? Thank you very much !

### ISSUE THREAD

**Issue by zsevenj** [limuhit/360-Image-Compression#1]

**Comment by limuhit** [comment]
Schedule:

1. Train baseline model without entropy by trainDDP_IMP.py
2. Train the whole model with the entropy by trainDDP_IMP_ENT.py
3. Extract the importance map by extract_codes.py
4. Train a post entropy model for the importance map by trainDDP_POST_ENT.py

Dataset: https://github.com/limuhit/pseudocylindrical_convolution
