### ISSUE TITLE
Flickr dataset download

### ISSUE THREAD

**Issue by xuezhongcailian** [limuhit/360-Image-Compression#3]
Hello, thanks for your perfect work and open source, I see that your dataset is from Flickr, how can I batch download images of the same size? I would like to batch download some other images of the same size and high resolution, I don't know how to do it, can you provide the code?f Thank you very much, my email is: 1294212648hh@gmail.com

**Comment by limuhit** [comment]
You can download the images, downsample, and crop them to the same size. If you ask for the method to crawl the URL of images, try python + [Selenium](https://www.selenium.dev/).
